### ISSUE TITLE
unknown directive "rtmp"

### ISSUE THREAD

**Issue by sunxuan1234** [glaciall/jtt1078-video-server#11]
我的nginx版本信息如下
nginx version: nginx/1.9.12
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --add-dynamic-module=/usr/local/nginx_http_flv/nginx-http-flv-module

为何include nginx_rtmp.conf后会出现这个报错提示
unknown directive "rtmp" in /usr/local/nginx/conf/nginx_rtmp.conf:4

**Comment by sunxuan1234** [comment]
抱歉，刚检查nginx.conf 忘了load module了

**Comment by glaciall** [comment]
呃，好的。。。
