### ISSUE TITLE
ADPCM测试正常，G711A杂音很大

### ISSUE THREAD

**Issue by CrazyDoraemon** [glaciall/jtt1078-video-server#18]
作者你好，感谢提供源码，测试后发现G711A转PCM后，播放有很大的杂音，一直滴滴响，ADPCM没有这个问题

**Comment by glaciall** [comment]
滴滴响？这不科学啊，只要不是很强烈的噪间的那种，都说明解码没问题的，更何况你是的滴滴响。你需要多试几台G711A的设备，或是把音频数据抽出来，使用ffplay -f alaw -ar 8000 -ac 1 -i xxoo.g711a来播放测试一下。另外，欢迎加群讨论。
