### ISSUE TITLE
G726_40方式 播放只有杂音,求解 音频格式确实为G726_40

### ISSUE THREAD

**Issue by dong692** [glaciall/jtt1078-video-server#25]
G726_40方式 播放只有杂音,求解 音频格式确实为G726_40

**Comment by glaciall** [comment]
这个没得救的，G726是网友贡献的代码，我自己都没有试过，我建议你可以找一下RTVS。

**Comment by dong692** [comment]
> 这个没得救的，G726是网友贡献的代码，我自己都没有试过，我建议你可以找一下RTVS。

好的谢谢
